# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				panda = true
				bee = true
				axolotl = true
				zoglin = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				allay = true
				skeleton = true
				llama = true
				bat = true
				frog = true
				husk = true
				hoglin = true
				camel = true
				rabbit = true
				silverfish = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				stray = true
				turtle = true
				shulker = true
				salmon = true
				wither_skeleton = true
				wandering_trader = true
				vex = true
				piglin_brute = true
				goat = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				horse = true
				vindicator = true
				phantom = true
				minecart = true
				ender_dragon = true
				evoker = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				snowball = true
				parrot = true
				creeper = true
				enderman = true
				chicken = true
				sniffer = true
				ravager = true
				donkey = true
				fox = true
				tropical_fish = true
				chest_minecart = true
				slime = true
				pillager = true
				iron_golem = true
				area_effect_cloud = true
				zombified_piglin = true
				piglin = true
				blaze = true
				cat = true
				zombie = true
				guardian = true
				ghast = true
				sheep = true
				player = true
				illusioner = true
				pufferfish = true
				villager = true
				wolf = true
				skeleton_horse = true
				zombie_villager = true
				tnt_minecart = true
				elder_guardian = true
				polar_bear = true
				strider = true
				painting = true
				cave_spider = true
				witch = true
				cod = true
				spider = true

			[light_sources.settings.entities.endermanoverhaul]
				savanna_enderman = true
				ice_spikes_enderman = true
				flower_fields_enderman = true
				desert_enderman = true
				coral_enderman = true
				end_enderman = true
				crimson_forest_enderman = true
				cave_enderman = true
				snowy_enderman = true
				dark_oak_enderman = true
				scarab = true
				end_islands_enderman = true
				badlands_enderman = true

			[light_sources.settings.entities.underground_jungle]
				mossy_skeleton = true
				jungle_zombie = true

			[light_sources.settings.entities.mutantmonsters]
				mutant_enderman = true
				mutant_creeper = true
				mutant_skeleton = true
				mutant_zombie = true

			[light_sources.settings.entities.additionaladditions]
				glow_stick = true

			[light_sources.settings.entities.snowyspirit]
				gingerbread_golem = true
				sled = true

			[light_sources.settings.entities.illagerinvasion]
				alchemist = true
				provoker = true
				archivist = true
				basher = true
				necromancer = true
				marauder = true

			[light_sources.settings.entities.hamsters]
				hamster = true

			[light_sources.settings.entities.naturalist]
				deer = true
				snail = true
				alligator = true
				rhino = true
				bluejay = true
				snake = true
				robin = true
				boar = true
				dragonfly = true
				tortoise = true
				duck = true
				butterfly = true
				bear = true
				sparrow = true
				lizard = true
				zebra = true
				rattlesnake = true
				canary = true
				firefly = true
				hippo = true
				coral_snake = true
				cardinal = true
				lion = true
				vulture = true
				bass = true
				giraffe = true
				elephant = true
				finch = true

			[light_sources.settings.entities.betternether]
				firefly = true
				flying_pig = true
				hydrogen_jellyfish = true
				skull = true
				jungle_skeleton = true
				naga = true

			[light_sources.settings.entities.immersive_aircraft]
				airship = true
				warship = true

			[light_sources.settings.entities.ribbits]
				ribbit = true

			[light_sources.settings.entities.ecologics]
				squirrel = true
				penguin = true

			[light_sources.settings.entities.create]
				stationary_contraption = true
				contraption = true
				crafting_blueprint = true

			[light_sources.settings.entities.dungeonnowloading]
				spawner_carrier = true
				chaos_spawner = true

			[light_sources.settings.entities.yungscavebiomes]
				ice_cube = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.crittersandcompanions]
				dragonfly = true
				jumping_spider = true
				leaf_insect = true
				shima_enaga = true
				koi_fish = true
				dumbo_octopus = true
				ferret = true
				otter = true
				sea_bunny = true
				red_panda = true

			[light_sources.settings.entities.creeperoverhaul]
				swamp_creeper = true
				bamboo_creeper = true
				jungle_creeper = true
				cave_creeper = true
				beach_creeper = true
				savannah_creeper = true
				spruce_creeper = true
				hills_creeper = true
				snowy_creeper = true
				badlands_creeper = true
				ocean_creeper = true
				dark_oak_creeper = true
				desert_creeper = true
				dripstone_creeper = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

			[light_sources.settings.entities.iceandfire]
				stymphalian_bird = true
				lightning_dragon = true
				siren = true
				fire_dragon_charge = true
				hydra_multipart = true
				ice_dragon_charge = true
				cylcops_multipart = true
				hydra = true
				ghost = true
				dragon_multipart = true
				cyclops = true
				sea_serpent = true
				pixie = true
				cockatrice = true
				sea_serpent_bubbles = true
				hippocampus = true
				myrmex_queen = true
				hippogryph = true
				gorgon = true
				troll = true
				fire_dragon = true
				myrmex_soldier = true
				ice_dragon = true
				deathworm = true
				multipart = true
				amphithere = true
				lightning_dragon_charge = true
				myrmex_worker = true

			[light_sources.settings.entities.bosses_of_mass_destruction]
				lich = true
				soul_star = true

			[light_sources.settings.entities.charm]
				moobloom = true
				coral_squid = true

			[light_sources.settings.entities.betterend]
				dragonfly = true
				cubozoa = true
				end_slime = true
				silk_moth = true
				end_fish = true

			[light_sources.settings.entities.caligo]
				strow = true
				deep_strow = true
				coppice = true

			[light_sources.settings.entities.friendsandfoes]
				glare = true
				copper_golem = true
				moobloom = true
				mauler = true
				iceologer = true
				wildfire = true
				crab = true
				rascal = true

			[light_sources.settings.entities.spider_caves]
				black_recluse = true

			[light_sources.settings.entities.amethyst_imbuement]
				player_egg_entity = true
				sardonyx_fragment = true

